# -*- coding: utf-8 -*-
"""exercicio_college.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQm0rUH8-JsLENBDpjPnqT0ezO3n87ZJ
"""

import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots

url='https://www.statlearning.com/s/College.csv'
College = pd.read_csv(url)
College[:2]

College2 = pd.read_csv(url, index_col=0)
College2[:2]

College3 = College.rename({'Unnamed: 0' : 'College'}, axis=1)
College3.set_index('College')
College=College3

College.describe()[:3]

ls = College[['Top10perc', 'Apps', 'Enroll']]
pd.plotting.scatter_matrix(College[['Top10perc', 'Apps', 'Enroll']], figsize=(5, 5));

fig, ax = subplots(figsize=(5, 5))
College.boxplot('Outstate', by='Private', ax=ax);

College['Elite'] = pd.cut(College['Top10perc'], [0, 0.5, 1  ], labels=['No', 'Yes'])

College['Elite'].value_counts()

fig, ax = subplots(figsize=(4,4))
College.boxplot('Outstate', by='Elite', ax=ax)

College.columns

fig, axes = subplots(nrows=2, ncols=2, figsize=(5,5))

College[['Accept', 'Apps']].plot.hist(ax=axes[0,0]);
College[['Grad.Rate', 'Elite', 'perc.alumni', 'Room.Board']].plot.hist(ax=axes[0,1]);
College[['Books', 'Expend', 'Personal']].plot.hist(ax=axes[1,0]);
College[['Top25perc', 'Top10perc', 'Enroll', 'F.Undergrad']].plot.hist(ax=axes[1,1]);