# -*- coding: utf-8 -*-
"""exercicio_boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Nl6q6jwufRKfquBOH89uGmyFnbEB_-o
"""

import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots

!pip install ISLP

from ISLP import load_data
Boston = load_data('Boston')
Boston.columns

Boston.describe()
Boston

# Linhas: 506
# Colunas: 13
# O que representam: Informações estatísticas sobre o ambiente de Boston
rows = Boston.shape[0]
cols = Boston.shape[1]

print("Linhas: {} Colunas: {}".format(rows, cols))

fig, axes = subplots(nrows=2, ncols=2, figsize=(5,5))
Boston.plot.scatter('crim', 'nox', ax=axes[0,0]);
Boston.plot.scatter('zn', 'chas', ax=axes[0,1]);
Boston.plot.scatter('rm', 'dis', ax=axes[1,0]);
Boston.plot.scatter('ptratio', 'lstat', ax=axes[1,1]);

# Há relação entre Status de baixa renda com crime per capta?

fig, ax = subplots(figsize=(5,5))
Boston.plot.scatter('crim', 'lstat', ax=ax);

# Maiores valores de crime, taxa e relação aluno-professor

crim = Boston['crim'].sort_values(ascending=False)
tax = Boston['tax'].sort_values(ascending=False)
ptratio = Boston['ptratio'].sort_values(ascending=False)

# print(crim[:5])
# print(tax[:5])
# print(ptratio[:5])

# Quantos suburbios são divisa do rio Charles

Boston['chas'].value_counts()

# Mediana da relação aluno-professor nas cidades
Boston['ptratio'].median()

# Menor mediana de casas ocupadas por donos e seus outros preditores?
med = min(Boston['medv'])
l = Boston[Boston['medv'] == med]
l

# Numero médio de quartos por habitação > 7 e >8
m7 = Boston[Boston['rm'] > 7]
m8 = Boston[Boston['rm'] > 8]

m7 = m7.shape[0]
m8 = m8.shape[0]
print("Número médio de quartos por habitação\nMaior que 7: {}\nMaior que 8: {}".format(m7,m8))