# -*- coding: utf-8 -*-
"""exercicio_auto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhvjzuZxXx_1GqueOTB1OFESfFFButOB
"""

import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots

url='https://www.statlearning.com/s/Auto.csv'
Auto = pd.read_csv(url, na_values='?')
Auto_n = Auto.dropna()
Auto=Auto_n

Auto.dtypes
#Qualitativas: name, origin
#Quantitativas: resto

r1 = np.max(Auto['mpg'] - np.min(Auto['mpg']))
r1

# Range de cada coluna quantitativa
ranges = {}
for col in Auto.select_dtypes(include=['float64', 'int64']):
  ranges[col] = np.max(Auto[col]) - np.min(Auto[col])
ranges

# Média de cada coluna quantitativa
means = {}
for col in Auto.select_dtypes(include=['float64', 'int64']):
  means[col] = np.mean(Auto[col])
means

# Desvio padrão de cada coluna quantitativa
dps = {}
for col in Auto.select_dtypes(include=['float64', 'int64']):
  dps[col] = np.std(Auto[col])
dps

# Remover linhas da 10 até 85
Auto_new = Auto.drop(Auto.index[10:85])
# Auto = remover
# Auto

# Rever média e variancia
means = {}
for col in Auto_new.select_dtypes(include=['float64', 'int64']):
  means[col] = np.mean(Auto_new[col])
print(means)

dps = {}
for col in Auto_new.select_dtypes(include=['float64', 'int64']):
  dps[col] = np.std(Auto_new[col])
print(dps)

fig, axes = subplots(nrows=2, ncols=2, figsize=(6, 6))
axes[0,0].plot(Auto['acceleration']);
Auto.boxplot('mpg', by='origin', ax=axes[0,1]);
axes[1,0].hist(Auto['cylinders']);
axes[1,0].hist(Auto['acceleration']);
Auto.plot.scatter('weight', 'mpg', ax=axes[1,1]);

Auto.columns