# -*- coding: utf-8 -*-
"""numeric2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U31NF4bo-C5R7j-1iHKicijKFkuT_G9m
"""

import random
import numpy as np
from matplotlib.pyplot import subplots

rng = np.random.default_rng(3)

fig, ax = subplots(figsize=(7,7))
x = rng.standard_normal(100)
y = rng.standard_normal(100)
ax.plot(x, y, 'o');
ax.set_xlabel("idade")
ax.set_ylabel("dinheiro")
ax.set_title("sei lá")

fig.set_size_inches((4,4))
fig

fig, axes = subplots(nrows=2, ncols=2, figsize=(15,5))
axes[0, 1].plot(x, y, 'o');
axes[0, 0].plot(np.sqrt(x), y, 'x');
axes[1, 0].plot(np.pow(x, 2), y, '^');
axes[1, 1].plot(x, np.pow(y, 1.5), '>');

fig, ax = subplots(figsize=(4,4))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1 / (1 + x**2))
ax.contour(x, y, f, levels=15);

fig, ax = subplots(figsize=(4,4))
ax.imshow(f);

seq1 = np.linspace(0, 10, 11)
seq1

seq2 = np.arange(0, 10)
seq2

A = np.array(np.arange(16)).reshape((4, 4))
A

# Selecionar valores
A[1, 2]

# Selecionar linhas
A[[0, 3]]

# Selecionar colunas
A[:, [0, 2]]

# Criar submatriz com linhas e colunas
A[[0, 2]] [:, [0,1]]
# Primeiro selecionamos as linhas e depois as colunas desejadas

# Outra alternativa
idx = np.ix_([0, 2], [0, 1])
A[idx]

import pandas as pd

url = "https://www.statlearning.com/s/Auto.csv"
Auto = pd.read_csv(url, na_values=['?'])
Auto['horsepower'].sum()

Auto_new = Auto.dropna()
print(Auto_new.shape)

Auto = Auto_new
print(Auto.columns)

idx_80=Auto['year'] > 80

# Auto[idx_80]
Auto[['mpg', 'horsepower']]

Auto_re = Auto.set_index('name')
Auto_re.columns

rows = ['amc rebel sst', 'ford torino']
Auto_re.loc[rows]
Auto_re.iloc[0, [0, 2, 3]]

# chamar primeira e quarta linha junto da segunda, quarta e quinta coluna
Auto_re.iloc[[0, 3], [1, 3, 4]]

# chamar linhas com o mesmo nome e colunas específicas
Auto_re.loc['ford galaxie 500', ['mpg', 'horsepower']]

# Mais seleções de linhas e colunas
## Criar um df com peso e origem de carros em que o ano é maior que 80
idx_80 = Auto_re['year']>80
Auto_re.loc[idx_80, ['weight', 'origin']]

# Fazer a mesma coisa da célula anterior
Auto_re.loc[lambda df: df['year'] > 80, ['weight', 'origin']]

# Achar o peso e origem dos carros com ano > 80 e cavalos > 130
Auto_re.loc[lambda df: (df['year'] > 80) & (df['horsepower'] < 130.0), ['weight', 'origin']]

# loops ?
## exemplo simples: ver o total de uma lista, somando cada valor multiplicado pelo peso
total = 0
for i in [2, 3, 19]:
  for j in [3, 2, 1]:
    total += i * j
print("total é {0}".format(total))

# função zip()
total = 0
for i, j in zip([2, 3, 19], [0.2, 0.3, 0.5]):
  total += i * j
print("total é {0}".format(total))

rng = np.random.default_rng(1)
A = rng.standard_normal((127, 5))
M = rng.choice([0, np.nan], p=[0.8, 0.2], size=A.shape)
A += M
D = pd.DataFrame(A, columns=['food', 'bar', 'pickle', 'snack', 'popcorn'])

D[:3]

for col in D.columns:
  template = 'Coluna "{0}" têm {1:.2%} valores faltando'
  print(template.format(col, np.isnan(D[col]).mean()))