# -*- coding: utf-8 -*-
"""numeric3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4ic9aH8UuT9qqPZIAN7FRIohdK9I3d7
"""

import numpy as np
from matplotlib.pyplot import subplots
import pandas as pd

Auto = pd.read_csv('https://www.statlearning.com/s/Auto.csv')

hp = Auto['horsepower']
mpg = Auto['mpg']

fig, ax = subplots(figsize=(4,4))
ax.plot(hp, mpg, 'x');

ax = Auto.plot.scatter('horsepower', 'mpg');

fig, axes = subplots(ncols=3, figsize=(5,5))
Auto.plot.scatter('horsepower', 'mpg', ax=axes[0]);

Auto.cylinders = pd.Series(Auto.cylinders, dtype='category')
Auto.cylinders.dtype

fig, ax = subplots(figsize=(4,4))
Auto.boxplot('mpg', by='cylinders', ax=ax);

fig, ax = subplots(figsize=(4,4))
Auto.hist('mpg', ax=ax);

pd.plotting.scatter_matrix(Auto, figsize=(4,4));

Auto['acceleration'].describe()