# -*- coding: utf-8 -*-
"""regressao_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVth990rjIjDVtLiqjyxZTAXwLeU00Bf
"""

# Regressão linear simples
# Regressão linear simples tem o formato y' = b0 + b1*x'
# b0 é chamado de inclinação (slope) e b1 é chamado interceptação
# O ajuste é feito com mínimos quadrados ou RSS
# RSS = somatório de (yi - y'i)^2. yi é o i-ésimo valor real de y, e y'i é o i-ésimo valor predito
# b1 = somatório de (x - ẍ)*(y-ÿ) / somatório de (x - ẍ)^2
# b0 = ÿ - b1*ẍ
# ÿ e ẍ são as médias

import numpy as np

# dados
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

#médias
x_mean = np.mean(x)
y_mean = np.mean(y)

# interceptação, parâmetro b1
b1 = np.sum((x - x_mean)*(y - y_mean)) / np.sum((x - x_mean)**2)

# inclinação, parâmetro b0
b0 = (y_mean - b1*x_mean)

print("Inclinação {} e interceptação {}".format(b0, b1))

predicted_y = b0 + b1*x

print("Valores reais: {}".format(y))
print("Valores preditos: {}".format(predicted_y))

#RSS = somatório de (yi - y'i)^2. yi é o i-ésimo valor real de y, e y'i é o i-ésimo valor predito
rss = (y - predicted_y)**2
print("Valores de resíduo para cada Xi: {}".format(rss))

#Regressão Linear usando scikit-learning
import numpy as np
from sklearn.linear_model import LinearRegression

# dados
x = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
y = np.array([2, 4, 5, 4, 5])

# Modelo
model = LinearRegression()
model.fit(x, y)

# parâmetros da regressão linear
intercept = model.intercept_ #Parâmetro b0, interceptação
slope = model.coef_[0] #Parâmetro b1, inclinação

print("Inclinação {} e interceptação {}".format(intercept, slope))

y_pred = model.predict(x)
print("Valores reais: {}".format(y))
print("Valores preditos: {}".format(y_pred))

#RSS
rss = y - y_pred
print("Valores de RSS: {}".format(rss))